#!/bin/sh
#.
#


case "$1" in
  start)
    insmod /lib/modules/$(uname -r)/rpi_gpio_drv.ko gpio_nr=47
    ;;
  stop)
    rmmod rpi_gpio_drv.ko
    ;;
  restart|reload)
    # Delete PID file
    killall -9 rpi_gpio
    rmmod rpi_gpio_drv.ko
    insmod /lib/modules/$(uname -r)/rpi_gpio_drv.ko gpio_nr=47
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
